### ISSUE TITLE
Kotlin Extension Functions

### ISSUE THREAD

**Issue by etonotieno** [kioko/paybill-manager#10]
Hello I have a suggestion about the way you're mapping your data models. you can use extension functions. this would mean less objects to create or inject.

**Comment by thomaskioko** [comment]
@CodeZilla7 I used this approach initially but now that I've switched to using Clean Architecture, you want to have independent modules. Think about seperstion of concern. I'm might also merge the presentation module into the app module

You can also make a PR and we can look at it. 😀
